### ISSUE TITLE
Discrepancy in training and dev utterance count

### ISSUE THREAD

**Issue by max-nullid** [SVDDChallenge/CtrSVDD_Utils#1]
Thanks for organising the event!

I was working with the datasets listed in readme and found the final utterance count doesn't match with that mentioned in you[ Evaluation Plan](https://challenge.singfake.org/SVDD_Challenge_2024_Eval_Plan_v0.1.pdf).

Table 1 mentions that a total of 84,414 training utterances and 43,625 dev utterances. However, after downloading and preprocessing all the datasets, I ended up with only 84,404 training utterances and 41,728 dev utterances.

Steps taken:

1. Downloaded and unzipped the original dataset along with the additional four datasets: Oniku, Ofuton, Kiritan, JVS
2. Ran the `segment.py` script to segment the latter four dataset.
3. Sum up the total number of training and dev utterances across all five datasets.

While I was processing the data, I did notice there's an inconsistency in the availability of timestamp files, like some dataset only has the timestamps files for the dev split and some has both. e.g., Kiritan only has the timestamp tags for the dev split. I was wondering is this inconsistency by designed, or perhaps I have missed something?

**Comment by xieyuankun** [comment]
I guess your set of 41,728 dev utterances does not include the 1,372 bonafide utterances from jvs_dev and the 525 bonafide utterances from kirtan_dev. As a result, the total number of dev utterances is 43,625. By the way, my training set also consists of 84,404 utterances.

**Comment by max-nullid** [comment]
@xieyuankun Thanks for catching that! Totally thought I had segmented those two datasets, but guess I didn't. 
btw, later I noticed the train.txt has exactly 84,404 rows, so it seems like that's just how it is.

**Comment by yzyouzhang** [comment]
Thank you for the discussion. Yes, it is 12,169 + 72,235 = 84,404 training utterances.
